config/routes.rb
Rails.application.routes.draw do
  resources :queries, only: [:create, :index, :new, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
class Query < ApplicationRecord
    validates :principal, :rate, :years, :total, presence: true

    def calculate_total
      if check_valid  
         total = principal * (1 + (rate * years*0.01)) 
      else
          total = 0
      end   
    end

    def check_vals
        return total > 0 && principal > 0 && rate > 0 && years > 0
    end

    def check_valid
        return principal && rate && years
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    @queries = Query.all

  end
  def new
  end  
  def create
      @query = Query.new(query_params)
      
      @query.total = @query.calculate_total
    
      if !@query.check_valid
            flash[:message] = "Values cant be nil"
           redirect_to queries_url
       elsif !@query.check_vals 
           flash[:message] = "Values need to be greater than zero"
           redirect_to queries_url
          
       elsif @query.save
        flash[:total] = @query.total
        redirect_to queries_url
      else
        flash[:error] = errors.full_error_messages
        redirect_to queries_url
       #add redirection
      end  
  end

  def destroy
    if params[:id]!= "all"
      query = Query.find(params[:id])
      query.destroy
    else
      queries = Query.all
      queries.each do |q|
        q.destroy
      end
    end
    redirect_to queries_url
  end

  protected
  
   def query_params
      params.require(:query).permit(:principal, :rate, :years)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CICalc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/queries/create.html.erb
<h1>Queries#create</h1>
<p>Find me in app/views/queries/create.html.erb</p>

app/views/queries/destroy.html.erb
<h1>Queries#destroy</h1>
<p>Find me in app/views/queries/destroy.html.erb</p>

app/views/queries/index.html.erb
<h1>Calculate Interest</h1>
<%principal=0%>
<%rate=0%>
<%years=0%>
<form action="/queries" method="post">
<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
   <div class="form">
        <div  class="msg"><%=flash[:message] %></div>
        <label for="principal" class="label" >Principal</label>
        <input id="principal" type="text" name="query[principal]" value="<%principal%>" class="formField">
            <label for="principal" class="label">Rate</label>
        <input id="rate" type="text" name="query[rate]" value="<%rate%>"class="formField" >
            <label for="years" class="label">Years</label>
        <input id="years" type="text" name="query[years]" value="<%years%>" class="formField">
        <input type="submit" value="Calculate the Interest" class="btn">
    </div>
</form>
<%if flash[:total]%>
<div class="total">
   Total with Interest: <%= flash[:total] %>
</div> 
<%end%>
<div class="queryTable">
<table style="width:30% ">
  <tr>
    <th>Principal</th>
    <th>Rate</th>
    <th>Years</th>
    <th>Total</th>
    <th> 
    <form action="<%=query_url(:all)%>" method="POST">
     <input type="hidden" name="_method" value="DELETE"/>
     <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

     <input type="submit" value="Delete All" class="btn2"/> 
  </form> 
  
  </th> 
  </tr>
  <%@queries = @queries.reverse%>
  <%i=0%>
<% @queries.each do |q| %>
     <tr>
    <td><%= q.principal %></td>
    <td><%=q.rate%></td>
    <td><%=q.years%></td>
    <td><%=q.total%></td>
    <form action="<%=query_url(q.id)%>" method="POST">
     <input type="hidden" name="_method" value="DELETE"/>
     <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
     <td><input type="submit" value="Delete" class="btn2"/> <br></td>
  </form>
  </tr>  
   
<%end%>

</table>
</div>

app/views/queries/new.html.erb
<form action="/queries" method="post">
<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
   <label for="principal">Principal</label>
   <input id="principal" type="text" name="query[principal]">
    <label for="principal">Rate</label>
   <input id="rate" type="text" name="query[rate]">
    <label for="years">Years</label>
   <input id="years" type="text" name="query[years]">
   <input type="submit" value="Calculate the Compund Interest" class="btn">

</form>